micronaut:
  application:
    name: clean_arch

datasources:
  default:
    url: jdbc:h2:mem:devDb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2

jpa:
  default:
    entity-scan:
      packages: 'br.com.clean.arch.provider.entity'
      enabled: true
    properties:
        show_sql: true
#kafka:
# bootstrap:
#  servers: localhost:9092
